name: Nightly ISO Build

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build ISO
      run: |
        mkdir -p release
        bin/iso-make

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: aeris-iso-${{ github.run_number }}
        path: release/*.iso
        retention-days: 30
